### ISSUE TITLE
Cannot install - 404 error on URL

### ISSUE THREAD

**Issue by dorothyDorothy** [scaffold-eth/scaffold-eth-challenges#323]
Tried installing challenge-1-decentralized-staking using yarn and then using npm, both failed

**Yarn install fails.**  
Looks like it is the missing content at https://codeload.github.com/hugomrdias/concat-stream/tar.gz/057bc7b5d6d8df26c8cf00a3f151b6721a0a8034

Here are some details:

> Yarn version: 
  1.22.19

> Node version: 
>   18.17.1
> 
> Platform: 
>   linux x64
> 
> Trace: 
>   Error: https://codeload.github.com/hugomrdias/concat-stream/tar.gz/057bc7b5d6d8df26c8cf00a3f151b6721a0a8034: Request failed "404 Not Found"
>       at ResponseError.ExtendableBuiltin (/<local_path>/.nvm/versions/node/v18.17.1/lib/node_modules/yarn/lib/cli.js:696:66)
>       at new ResponseError (/<local_path>/.nvm/versions/node/v18.17.1/lib/node_modules/yarn/lib/cli.js:802:124)
>       at Request.<anonymous> (<local_path>/.nvm/versions/node/v18.17.1/lib/node_modules/yarn/lib/cli.js:66215:16)
>       at Request.emit (node:events:514:28)
>       at module.exports.Request.onRequestResponse (<local_path>/.nvm/versions/node/v18.17.1/lib/node_modules/yarn/lib/cli.js:141767:10)
>       at ClientRequest.emit (node:events:514:28)
>       at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
>       at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
>       at TLSSocket.socketOnData (node:_http_client:541:22)
>       at TLSSocket.emit (node:events:514:28)

**npm fails**
Here are the details:

> /<local_path>/.npm/_logs/2023-08-31T13_14_33_660Z-debug-0.log
> # npm resolution error report
> 
> While resolving: @scaffold-eth/react-app@1.0.0
> Found: @testing-library/dom@6.16.0
> node_modules/@testing-library/dom
>   dev @testing-library/dom@"^6.12.2" from @scaffold-eth/react-app@1.0.0
>   packages/react-app
>     @scaffold-eth/react-app@1.0.0
>     node_modules/@scaffold-eth/react-app
>       workspace packages/react-app from the root project
> 
> Could not resolve dependency:
> peer @testing-library/dom@">=7.21.4" from @testing-library/user-event@12.8.3
> node_modules/@testing-library/user-event
>   @testing-library/user-event@"^12.1.8" from @scaffold-eth/react-app@1.0.0
>   packages/react-app
>     @scaffold-eth/react-app@1.0.0
>     node_modules/@scaffold-eth/react-app
>       workspace packages/react-app from the root project
> 
> Fix the upstream dependency conflict, or retry
> this command with --force or --legacy-peer-deps
> to accept an incorrect (and potentially broken) dependency resolution.

**Comment by dorothyDorothy** [comment]
Tried on node version v18.16.0 and it didn't work. Tried again on node v18.17.1 but forgot to change branch first (I think) anyway, 2nd time lucky.
Still getting 
`https://codeload.github.com/hugomrdias/concat-stream/tar.gz/057bc7b5d6d8df26c8cf00a3f151b6721a0a8034: Request failed \"404 Not Found\`
Hopefully not an issue

**Comment by ottodevs** [comment]
> Tried on node version v18.16.0 and it didn't work. Tried again on node v18.17.1 Still getting `https://codeload.github.com/hugomrdias/concat-stream/tar.gz/057bc7b5d6d8df26c8cf00a3f151b6721a0a8034: Request failed \"404 Not Found\` `yarn start` fails

Take a look to my solution, I did it for challenge-2 branch, but it should also fix this challenge-1 as it is the same issue. I will do another PR for that one as well

**Comment by Maximesol** [comment]
The probleme still the same, do we have a solution ?

**Comment by fremdelve** [comment]
> > Tried on node version v18.16.0 and it didn't work. Tried again on node v18.17.1 Still getting `https://codeload.github.com/hugomrdias/concat-stream/tar.gz/057bc7b5d6d8df26c8cf00a3f151b6721a0a8034: Request failed \"404 Not Found\` `yarn start` fails
> 
> Take a look to my solution, I did it for challenge-2 branch, but it should also fix this challenge-1 as it is the same issue. I will do another PR for that one as well

Hi @ottodevs, for Challenge-0, I tried the changes you made for the dependencies and I was able to install properly the dependencies and then running yarn chain, but when trying yarn deploy I'm getting several errors(guessing that they are maybe related to the openzepellin versions, mine are "@openzeppelin/contracts": "^4.3.3" and "@openzeppelin/contracts-upgradeable": "^4.4.1", ). Did you face any similar problem? 

The errors are:

TypeError: Function has override specified but does not override anything.
  --> contracts/YourCollectible.sol:40:16:
   |
40 |     ) internal override(ERC721, ERC721Enumerable) {
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Invalid contracts specified in override list: "ERC721" and "ERC721Enumerable".
  --> contracts/YourCollectible.sol:40:16:
   |
40 |     ) internal override(ERC721, ERC721Enumerable) {
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: This contract: 
  --> @openzeppelin/contracts/token/ERC721/ERC721.sol:19:1:
   |
19 | contract ERC721 is Context, ERC165, IERC721, IERC721Metadata {
   | ^ (Relevant source part starts here and spans across multiple lines).
Note: This contract: 
  --> @openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol:14:1:
   |
14 | abstract contract ERC721Enumerable is ERC721, IERC721Enumerable {
   | ^ (Relevant source part starts here and spans across multiple lines).

TypeError: Function needs to specify overridden contract "ERC721URIStorage".
  --> contracts/YourCollectible.sol:63:9:
   |
63 |         override(ERC721, ERC721Enumerable)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: This contract: 
  --> @openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol:12:1:
   |
12 | abstract contract ERC721URIStorage is IERC4906, ERC721 {
   | ^ (Relevant source part starts here and spans across multiple lines).

TypeError: Derived contract must override function "_beforeTokenTransfer". Two or more base classes define function with same name and parameter types.
  --> contracts/YourCollectible.sol:10:1:
   |
10 | contract YourCollectible is
   | ^ (Relevant source part starts here and spans across multiple lines).
Note: Definition in "ERC721": 
   --> @openzeppelin/contracts/token/ERC721/ERC721.sol:437:5:
    |
437 |     function _beforeTokenTransfer(address from, address to, uint256 firstTokenId, uint256 batchSize) internal virtual {}
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: Definition in "ERC721Enumerable": 
  --> @openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol:60:5:
   |
60 |     function _beforeTokenTransfer(
   |     ^ (Relevant source part starts here and spans across multiple lines).

TypeError: Wrong argument count for function call: 3 arguments given but expected 4.
  --> contracts/YourCollectible.sol:41:9:
   |
41 |         super._beforeTokenTransfer(from, to, tokenId);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ottodevs** [comment]
Hi @fremdelve and @Maximesol I just would like to suggest taking a look to this other repo: https://github.com/scaffold-eth/se-2-challenges/, where there is lot of effort put into adapting the challenges to version 2 of scaffold eth, and most of the issues we were discussing here were already fixed.

I solved most of the challenges by just using that other repo instead. This one seems abandoned for some months now.
